id: PCCEECD4A
initial_creation_type: ocr
source_metadata:
  volumes:
    5e4e01b335f74bc680874f21cdc47752:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: སྒྲོལ་མའི་སྒྲུབ་ཐབས་སྤྱིའི་མངོན་པར་རྟོགས་པ།
      total_pages: 1856
      volume_number: 14
